name: Publish to GitHub Packages

on:
    push:
        branches: [release]

jobs:
    publish:
        runs-on: ubuntu-latest
        permissions:
            contents: read
            packages: write
        steps:
            - uses: actions/checkout@v4

            - uses: pnpm/action-setup@v4
              with:
                  version: 9

            - uses: actions/setup-node@v4
              with:
                  node-version: '18'
                  registry-url: 'https://npm.pkg.github.com'
                  cache: 'pnpm'

            - run: pnpm install
            - run: pnpm prettier-check
            - run: pnpm build

            - run: pnpm publish --no-git-checks
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
